### ISSUE TITLE
Getting font awesome icons onto blog?

### ISSUE THREAD

**Issue by Kentoseth** [hdra/pelican-cait#8]
Hello there,

I see you have implemented the "envelope/email" icon very nicely on your "contact" page. I am trying to do the same for: gautengpug.github.io

Under "Social", you will see a GitHub icon, and now I would like to implement the "envelope" icon there as well.

If you would like to see the actual code of the site, it is here:

https://github.com/gautengpug/site_generate

Your help will be much appreciated!

**Comment by hdra** [comment]
I am not sure what you mean, but if you want to use the envelope icon, you don't have to use the whole Pelican-cait theme. You can simply use the icon directly with font-awesome

**Comment by Kentoseth** [comment]
@hdra : Can you explain how this can be done:

"You can simply use the icon directly with font-awesome"?

As that is what I am trying to do, but the icon isn't showing up for some reason.

**Comment by hdra** [comment]
You can read more about it here: http://fortawesome.github.io/Font-Awesome/

**Comment by Kentoseth** [comment]
Okay thanks.
